(in-package #:cl-stack-pathlib)

;;; In-memory VFS — proves the filesystem protocol; useful for tests & virtual trees.
;;; Entries: :dir | (:file vector timestamp) keyed by posix absolute path string.

(defclass memory-filesystem (filesystem)
  ((root :initform (make-hash-table :test #'equal) :reader memory-fs-root)
   (cwd :initform "/" :accessor memory-fs-cwd)
   (home :initform "/home" :accessor memory-fs-home))
  (:default-initargs :name "memory"))

(defun make-memory-filesystem (&key (cwd "/") (home "/home"))
  (let ((fs (make-instance 'memory-filesystem)))
    (setf (memory-fs-cwd fs) cwd
          (memory-fs-home fs) home)
    (setf (gethash "/" (memory-fs-root fs)) :dir)
    (fs-mkdir fs home :parents t :exist-ok t)
    fs))

(defun %mem-key (fs pathname)
  (let* ((pn (if (pathnamep pathname) pathname (fs-parse fs pathname)))
         (abs (if (uiop:absolute-pathname-p pn)
                  pn
                  (fs-join fs (memory-fs-cwd fs) pn)))
         (s (or (uiop:unix-namestring (uiop:ensure-pathname abs :want-pathname t))
                (namestring abs))))
    (cond ((or (string= s "") (string= s ".")) (memory-fs-cwd fs))
          ((char= (char s 0) #\/) (if (and (> (length s) 1) (char= (char s (1- (length s))) #\/))
                                      (subseq s 0 (1- (length s)))
                                      (if (string= s "/") "/" s)))
          (t s))))

(defun %mem-dir-key (key)
  (if (or (string= key "/") (char= (char key (1- (length key))) #\/))
      key
      key))

(defmethod fs-parse ((fs memory-filesystem) designator &key directory)
  (let ((pn (etypecase designator
              (pathname designator)
              (string (uiop:parse-unix-namestring designator))
              (path (path-pathname designator)))))
    (if directory (uiop:ensure-directory-pathname pn) pn)))

(defmethod fs-join ((fs memory-filesystem) base relative)
  (uiop:merge-pathnames*
   (fs-parse fs relative)
   (uiop:ensure-directory-pathname (fs-parse fs base))))

(defmethod fs-parent ((fs memory-filesystem) pathname)
  (uiop:pathname-parent-directory-pathname (fs-parse fs pathname)))

(defmethod fs-name ((fs memory-filesystem) pathname)
  (%file-namestring* (fs-parse fs pathname)))

(defmethod fs-absolute ((fs memory-filesystem) pathname &key (defaults nil))
  (let ((pn (fs-parse fs pathname))
        (base (fs-parse fs (or defaults (memory-fs-cwd fs)) :directory t)))
    (if (uiop:absolute-pathname-p pn) pn (uiop:merge-pathnames* pn base))))

(defmethod fs-resolve ((fs memory-filesystem) pathname &key (strict t))
  (let* ((abs (fs-absolute fs pathname))
         (key (%mem-key fs abs))
         (ent (gethash key (memory-fs-root fs))))
    (when (and strict (null ent))
      (error 'path-not-found :filesystem fs :path abs))
    abs))

(defmethod fs-normpath ((fs memory-filesystem) pathname)
  (let ((pn (fs-parse fs pathname)))
    (multiple-value-bind (abs? stack dir?) (%collapse-dot-segments pn)
      (fs-parse fs
                (cond ((and abs? (null stack)) "/")
                      (abs? (format nil "/~{~A~^/~}" stack))
                      ((null stack) ".")
                      (t (format nil "~{~A~^/~}" stack)))
                :directory dir?))))

(defmethod fs-expanduser ((fs memory-filesystem) pathname)
  (let* ((pn (fs-parse fs pathname))
         (s (or (uiop:unix-namestring pn) "")))
    (if (and (plusp (length s)) (char= (char s 0) #\~))
        (fs-join fs (memory-fs-home fs)
                 (if (and (> (length s) 1) (char= (char s 1) #\/))
                     (subseq s 2)
                     (subseq s 1)))
        pn)))

(defmethod fs-exists-p ((fs memory-filesystem) pathname)
  (let ((key (%mem-key fs (fs-absolute fs pathname))))
    (nth-value 1 (gethash key (memory-fs-root fs)))))

(defmethod fs-file-p ((fs memory-filesystem) pathname)
  (let ((ent (gethash (%mem-key fs (fs-absolute fs pathname)) (memory-fs-root fs))))
    (and (consp ent) (eq (car ent) :file))))

(defmethod fs-directory-p ((fs memory-filesystem) pathname)
  (let ((key (%mem-key fs (fs-absolute fs pathname))))
    (eq (gethash key (memory-fs-root fs)) :dir)))

(defmethod fs-symlink-p ((fs memory-filesystem) pathname)
  (let ((ent (gethash (%mem-key fs (fs-absolute fs pathname)) (memory-fs-root fs))))
    (and (consp ent) (eq (car ent) :symlink))))

(defmethod fs-readable-p ((fs memory-filesystem) pathname)
  (fs-exists-p fs pathname))

(defmethod fs-writable-p ((fs memory-filesystem) pathname)
  (or (fs-exists-p fs pathname)
      (fs-directory-p fs (fs-parent fs (fs-absolute fs pathname)))))

(defmethod fs-executable-p ((fs memory-filesystem) pathname)
  (declare (ignore pathname))
  nil)

(defmethod fs-file-size ((fs memory-filesystem) pathname)
  (let ((ent (gethash (%mem-key fs (fs-absolute fs pathname)) (memory-fs-root fs))))
    (unless (and (consp ent) (eq (car ent) :file))
      (error 'path-not-found :filesystem fs :path pathname))
    (length (second ent))))

(defmethod fs-last-modified ((fs memory-filesystem) pathname)
  (let ((ent (gethash (%mem-key fs (fs-absolute fs pathname)) (memory-fs-root fs))))
    (unless (and (consp ent) (eq (car ent) :file))
      (error 'path-not-found :filesystem fs :path pathname))
    (third ent)))

(defmethod fs-iterdir ((fs memory-filesystem) pathname)
  (let* ((abs (fs-absolute fs pathname :defaults (memory-fs-cwd fs)))
         (prefix (%mem-key fs abs))
         (prefix (if (string= prefix "/") "/" (concatenate 'string prefix "/")))
         (out '()))
    (unless (fs-directory-p fs abs)
      (error 'path-not-found :filesystem fs :path abs))
    (maphash (lambda (k v)
               (declare (ignore v))
               (when (and (uiop:string-prefix-p prefix k)
                          (not (string= k (%mem-key fs abs)))
                          (not (find #\/ k :start (length prefix))))
                 (push (fs-parse fs k) out)))
             (memory-fs-root fs))
    (nreverse out)))

(defmethod fs-glob ((fs memory-filesystem) pathname pattern &key recursive)
  (let* ((base (fs-absolute fs pathname))
         (prefix (%mem-key fs base))
         (prefix (if (string= prefix "/") "/" (concatenate 'string prefix "/")))
         (out '()))
    (maphash (lambda (k v)
               (declare (ignore v))
               (when (and (uiop:string-prefix-p prefix k)
                          (if recursive
                              (pathname-match-p k (merge-pathnames pattern "**/*"))
                              t))
                 (let ((name (file-namestring k)))
                   (when (and name (pathname-match-p name pattern))
                     (push (fs-parse fs k) out)))))
             (memory-fs-root fs))
    (nreverse out)))

(defmethod fs-walk ((fs memory-filesystem) pathname &key (top-down t) follow-symlinks)
  (declare (ignore follow-symlinks))
  (let ((out '()))
    (labels ((walk* (dir)
               (let* ((entries (fs-iterdir fs dir))
                      (files (remove-if-not (lambda (p) (fs-file-p fs p)) entries))
                      (dirs (remove-if-not (lambda (p) (fs-directory-p fs p)) entries)))
                 (when top-down (push (list dir files dirs) out))
                 (dolist (d dirs) (walk* d))
                 (unless top-down (push (list dir files dirs) out)))))
      (walk* (fs-absolute fs pathname))
      (nreverse out))))

(defmethod fs-mkdir ((fs memory-filesystem) pathname &key (parents t) (exist-ok t))
  (let* ((abs (uiop:ensure-directory-pathname (fs-absolute fs pathname)))
         (key (%mem-key fs abs)))
    (when (fs-exists-p fs abs)
      (unless (and exist-ok (fs-directory-p fs abs))
        (error 'path-exists-error :filesystem fs :path abs))
      (return-from fs-mkdir abs))
    (let ((parent (fs-parent fs abs)))
      (if parents
          (unless (or (%pathname-root-p parent) (fs-directory-p fs parent))
            (fs-mkdir fs parent :parents t :exist-ok t))
          (unless (or (%pathname-root-p parent) (fs-directory-p fs parent))
            (error 'path-not-found :filesystem fs :path abs
                   :message "parent directory does not exist"))))
    (setf (gethash key (memory-fs-root fs)) :dir)
    abs))

(defmethod fs-rmdir ((fs memory-filesystem) pathname)
  (let ((key (%mem-key fs (fs-absolute fs pathname))))
    (unless (fs-directory-p fs pathname)
      (error 'path-not-found :filesystem fs :path pathname))
    (when (fs-iterdir fs pathname)
      (error 'path-error :filesystem fs :path pathname :message "directory not empty"))
    (remhash key (memory-fs-root fs))
    t))

(defmethod fs-unlink ((fs memory-filesystem) pathname &key (missing-ok nil))
  (let* ((key (%mem-key fs (fs-absolute fs pathname)))
         (ent (gethash key (memory-fs-root fs))))
    (unless ent
      (unless missing-ok
        (error 'path-not-found :filesystem fs :path pathname))
      (return-from fs-unlink nil))
    (when (eq ent :dir)
      (error 'path-error :filesystem fs :path pathname :message "is a directory"))
    (remhash key (memory-fs-root fs))
    t))

(defmethod fs-touch ((fs memory-filesystem) pathname &key (exist-ok t))
  (let* ((abs (fs-absolute fs pathname))
         (key (%mem-key fs abs)))
    (if (gethash key (memory-fs-root fs))
        (unless exist-ok
          (error 'path-exists-error :filesystem fs :path abs))
        (progn
          (fs-mkdir fs (fs-parent fs abs) :parents t :exist-ok t)
          (setf (gethash key (memory-fs-root fs))
                (list :file (make-array 0 :element-type '(unsigned-byte 8)) (get-universal-time)))))
    abs))

(defmethod fs-rename ((fs memory-filesystem) source target &key (replace t))
  (let* ((sk (%mem-key fs (fs-absolute fs source)))
         (tk (%mem-key fs (fs-absolute fs target)))
         (ent (gethash sk (memory-fs-root fs))))
    (unless ent (error 'path-not-found :filesystem fs :path source))
    (when (and (not replace) (gethash tk (memory-fs-root fs)))
      (error 'path-exists-error :filesystem fs :path target))
    (setf (gethash tk (memory-fs-root fs)) ent)
    (remhash sk (memory-fs-root fs))
    (fs-parse fs tk)))

(defmethod fs-copy ((fs memory-filesystem) source target &key (replace t))
  (let* ((sk (%mem-key fs (fs-absolute fs source)))
         (tk (%mem-key fs (fs-absolute fs target)))
         (ent (gethash sk (memory-fs-root fs))))
    (unless ent (error 'path-not-found :filesystem fs :path source))
    (when (and (not replace) (gethash tk (memory-fs-root fs)))
      (error 'path-exists-error :filesystem fs :path target))
    (setf (gethash tk (memory-fs-root fs))
          (if (and (consp ent) (eq (car ent) :file))
              (list :file (copy-seq (second ent)) (get-universal-time))
              ent))
    (fs-parse fs tk)))

(defmethod fs-create-symlink ((fs memory-filesystem) link target)
  (let ((key (%mem-key fs (fs-absolute fs link))))
    (setf (gethash key (memory-fs-root fs))
          (list :symlink (%mem-key fs (fs-absolute fs target))))
    (fs-parse fs key)))

(defmethod fs-read-symlink ((fs memory-filesystem) pathname)
  (let ((ent (gethash (%mem-key fs (fs-absolute fs pathname)) (memory-fs-root fs))))
    (unless (and (consp ent) (eq (car ent) :symlink))
      (error 'path-error :filesystem fs :path pathname :message "not a symlink"))
    (fs-parse fs (second ent))))

(defmethod fs-read-bytes ((fs memory-filesystem) pathname)
  (let ((ent (gethash (%mem-key fs (fs-absolute fs pathname)) (memory-fs-root fs))))
    (unless (and (consp ent) (eq (car ent) :file))
      (error 'path-not-found :filesystem fs :path pathname))
    (copy-seq (second ent))))

(defmethod fs-write-bytes ((fs memory-filesystem) pathname bytes
                           &key (append nil) if-exists if-does-not-exist)
  (declare (ignore if-exists if-does-not-exist))
  (let* ((abs (fs-absolute fs pathname))
         (key (%mem-key fs abs))
         (old (gethash key (memory-fs-root fs)))
         (vec (if (and append (consp old) (eq (car old) :file))
                  (concatenate '(vector (unsigned-byte 8)) (second old) bytes)
                  (coerce bytes '(vector (unsigned-byte 8))))))
    (fs-mkdir fs (fs-parent fs abs) :parents t :exist-ok t)
    (setf (gethash key (memory-fs-root fs)) (list :file vec (get-universal-time)))
    abs))

(defmethod fs-make-temp ((fs memory-filesystem) &key (directory "/tmp") (prefix "tmp-") (suffix ""))
  (fs-mkdir fs directory :parents t :exist-ok t)
  (fs-parse fs (format nil "~A/~A~A~A"
                       (string-right-trim "/" (%mem-key fs (fs-absolute fs directory)))
                       prefix (get-universal-time) suffix)))

(defmethod fs-same-p ((fs memory-filesystem) a b)
  (string= (%mem-key fs (fs-absolute fs a))
           (%mem-key fs (fs-absolute fs b))))

(defmethod fs-as-uri ((fs memory-filesystem) pathname)
  (format nil "memory://~A" (%mem-key fs (fs-absolute fs pathname))))
