(defpackage #:cl-stack-pathlib
  (:nicknames #:stack-pathlib)
  (:use #:cl)
  (:export
   ;; --- filesystem protocol (Java NIO FileSystem SPI-shaped) ---
   #:filesystem
   #:filesystem-p
   #:filesystem-name
   #:filesystem-separator
   #:*filesystem*
   #:with-filesystem
   #:register-uri-scheme
   #:uri-scheme-handler
   #:list-uri-schemes
   #:uri-scheme
   ;; protocol generics — specialize per backend
   #:fs-parse
   #:fs-join
   #:fs-parent
   #:fs-name
   #:fs-absolute
   #:fs-resolve
   #:fs-normpath
   #:fs-expanduser
   #:fs-exists-p
   #:fs-file-p
   #:fs-directory-p
   #:fs-symlink-p
   #:fs-readable-p
   #:fs-writable-p
   #:fs-executable-p
   #:fs-file-size
   #:fs-last-modified
   #:fs-iterdir
   #:fs-glob
   #:fs-walk
   #:fs-mkdir
   #:fs-rmdir
   #:fs-unlink
   #:fs-touch
   #:fs-rename
   #:fs-copy
   #:fs-create-symlink
   #:fs-read-symlink
   #:fs-read-bytes
   #:fs-write-bytes
   #:fs-make-temp
   #:fs-same-p
   #:fs-as-uri
   ;; backends
   #:local-filesystem
   #:make-local-filesystem
   #:memory-filesystem
   #:make-memory-filesystem
   #:zip-filesystem
   #:zip-filesystem-p
   #:zip-filesystem-archive
   #:make-zip-filesystem
   #:zip-path
   #:write-zip-bytes
   #:write-zip-file
   #:zip-tree
   #:clear-zip-filesystem-cache
   ;; --- path value (bound to a filesystem) ---
   #:path
   #:path-p
   #:path-filesystem
   #:path-pathname                     ; escape hatch: pathname within that FS
   #:make-path
   #:ensure-path
   ;; facade (pathlib / NIO Path+Files DX)
   #:join
   #:joinpath
   #:from-list
   #:components
   #:parts
   #:parent
   #:parents
   #:with-parent
   #:name
   #:with-name
   #:base
   #:stem
   #:with-base
   #:with-stem
   #:extension
   #:suffix
   #:suffixes
   #:with-extension
   #:with-suffix
   #:add-extension
   #:drop-extension
   #:root-p
   #:empty-p
   #:absolute-p
   #:relative-p
   #:directory-pathname-p
   #:starts-with-p
   #:ends-with-p
   #:match-p
   #:absolute
   #:resolve
   #:expanduser
   #:normpath
   #:cwd
   #:home
   #:as-namestring
   #:as-posix
   #:as-uri
   #:to-string
   #:from-string
   #:ensure-directory
   #:ensure-string
   #:relative-to
   #:relative-to-p
   #:under
   #:same-p
   #:path-equal
   #:exists-p
   #:file-p
   #:directory-p
   #:symlink-p
   #:readable-p
   #:writable-p
   #:executable-p
   #:file-size
   #:last-modified
   #:iterdir
   #:glob
   #:rglob
   #:walk
   #:mkdir
   #:rmdir
   #:unlink
   #:delete-path                      ; not CL:DELETE
   #:touch
   #:rename-path
   #:replace-path
   #:copy-path
   #:move-path
   #:create-symlink
   #:read-symlink
   #:make-temp-file
   #:make-temp-directory
   #:read-text
   #:write-text
   #:read-bytes
   #:write-bytes
   ;; conditions
   #:path-error
   #:path-error-path
   #:path-error-filesystem
   #:path-error-message
   #:path-not-found
   #:missing-parent
   #:path-exists-error
   #:not-relative-error
   #:unsupported-operation
   #:directory-not-empty
   ;; restarts (invoke via INVOKE-RESTART / helpers)
   #:retry
   #:create-parents
   #:create-file
   #:create-directory
   #:overwrite
   #:ignore-missing
   #:call-with-path-restarts
   #:with-path-restarts
   #:invoke-create-parents
   #:invoke-create-file
   #:invoke-create-directory
   #:invoke-overwrite
   #:invoke-ignore-missing
   #:invoke-retry
   #:auto-create-parents
   #:auto-create-file
   #:auto-overwrite
   #:auto-ignore-missing
   #:with-auto-create-parents
   #:with-auto-create-file
   #:with-auto-overwrite
   #:with-auto-ignore-missing))